myName = input ("what is your name?")
print(myName)
favoriteFood = input ("what is your favorite food?")
print("you are probably hungry for")
print(favoriteFood)
favoriteMusic = input ("what is your favorite music?")
print("and you are definitely getting your groove on to")
print(favoriteMusic)
placeToLive = input ("where do you live?" )
print("living in the amazing")
print(placeToLive)