nameOfFoods = input("name of the food?: ")
typeOfPlant = input("what is the name of the plant?:")
methodOfCooking = input("what is the method of cooking?: ")
wordToDescribeBurnedFood = input("what word describes burned food?: ")
diyItem = input("diyitem?: ")
print(methodOfCooking, nameOfFoods, "with", wordToDescribeBurnedFood,typeOfPlant, "on a bed of", diyItem)