print("=== Your Adventure Simulator ===")
print("""You'll be asked a bunch of questions then we'll make you up an amazing story with YOU as the star! """)
print()
name = input("Your name: ")
enemy = input("Your worst enemy's name: ")
superpower = input("Your superpower: ")
sidekick = input("Your trusty sidekick's name: ")
weapon = input("Your weapon of choice: ")
location = input("A mystical location: ")

print()
print("\033[31m'Our story begins as our hero'\033[0m", name, "approaches a foreboding castle in the heart of", location)
print("Suddenly a bolt of lightning strikes the ground at the feet of",  name)
print("Our final battle begins! shouts the evil", enemy, "clearly missing the fact that", name, "has the power of", superpower, "which means they'll win quite easily.")
print("With a confident smile", name, "brandishes their", weapon, "ready for the showdown.")
print("By their side stands", name, "'s trusty sidekick", sidekick, "who has always been there through thick and thin.")
print("\033[32m'As the sky darkens, the clash between'\033[0m", name, "and", enemy, "commences, echoing through the halls of the castle.")
print("Using their", superpower, name, "deftly dodges", enemy, "'s attacks, countering with their", weapon, "in a display of unparalleled skill.")
print("With the support of", sidekick, name, "gains the upper hand, and it becomes clear that the power of", superpower, "will secure their victory.")
print("\033[33m'In a final, decisive move'\033[0m", name, "overcomes", enemy, "ensuring peace for", location, "once more.")
print("As the dust settles", name, " and", sidekick, "stand triumphant, ready for their next adventure.")